name: build android

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - 'template.config.js'

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ./template
        run: |
          yarn install --frozen-lockfile
          npx app-icon init
          npx app-icon generate

      - name: Build apk
        working-directory: ./template
        env:
          ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo $ANDROID_KEYSTORE_B64 | base64 -d > android/app/release-key.jks
          cp .env.example .env
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Apk
          path: template/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
