name: ci

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: lint
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./template
        run: yarn install

      - name: Linting
        working-directory: ./template
        run: yarn lint
